# Generated by Django 4.2 on 2024-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('dots', models.URLField(verbose_name='dots')),
                ('pinterest', models.URLField(verbose_name='Pinterest')),
                ('google_plus', models.URLField(verbose_name='Google+')),
                ('v', models.URLField(verbose_name='V')),
                ('youtube', models.URLField(verbose_name='YouTube')),
                ('mail', models.URLField(verbose_name='Mail')),
            ],
        ),
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': 'Add Banner', 'verbose_name_plural': 'Add Banner'},
        ),
    ]
