# Generated by Django 4.2 on 2024-02-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesocial_alter_add_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Addvertising',
        ),
    ]
